#!/bin/sh
set -e

case "$1" in
    configure)
        # APT-Pin: Verhindert dass linuxmuster-linbo-gui7 installiert wird
        cat > /etc/apt/preferences.d/edulution-linbo-gui << 'EOF'
# Installed by edulution-linbo-gui7
Package: linuxmuster-linbo-gui7
Pin: release *
Pin-Priority: -1
EOF
        ;;
esac

#DEBHELPER#
exit 0
